fix:userchg

diff --git a/dkrun b/dkrun
--- a/dkrun
+++ b/dkrun
@@ -15,6 +15,12 @@ fi
 
 if [ "$dockertag" == "" ]; then goon=0;fi #tmp fix
 if [ "$1" == "--create" ] ;then goon=0;fi #passing to --create part
+#export dkrunwhoami=""
+#if [ "$1" == "--user" ] ;then 
+#	dkrunwhoami="$(whoami)"
+#	echo "Running as $dkrunwhoami"
+#
+#fi
 
 # Support running on MIGMW, starting on this script on WSL
 #wsl -d "Ubuntu-20.04" --cd  "$(pwd)" dkrunner
@@ -100,6 +106,25 @@ _xtraargs="$_dkrunmode $_dkrmstop $dknamearg $_dkhostname $dkextra $_dkport $_dk
 #echo "------------------------------2204"
 #echo "_xtraargs=$_xtraargs"
 #echo "------------------------------2204"
+
+#Run as USER
+export dkrunwhoami=""
+if [ "$1" == "--user" ] ;then
+		dockertagroot="$dockertag"
+	        dkrunwhoami="$(whoami)" && \
+		        echo "Running as $dkrunwhoami" && \
+		dockertag="$dockertag-$dkrunwhoami"
+		#@STCIssue If image does not exist ??
+		echo " Testing if image: $dockertagroot"
+		docker inspect $dockertagroot && \
+			echo "Root Tag Exist" && \
+			echo "Dockertag now : $dockertag" || \
+			(echo "DKBuildUser Required" i&& \
+			echo "$BDIR/dkbuilduser" && \
+			exit 1)
+
+	
+fi
 
 #DISPLAY
 _display="-e DISPLAY=$DISPLAY"
